apiVersion: v1
kind: Pod
metadata:
  name: super-secret
  namespace: development
spec:
  containers:                         
  - name: demo-pod                
    image: nginx                    

---
apiVersion: v1
kind: Pod
metadata:
  name: privileged
  namespace: development
spec:
  containers:                         
  - name: privileged                
    image: nginx                    
    securityContext:
      privileged: true

